/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-08-16 11:53:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class addflight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<title>Populate Source Airport List</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("   <form action=\"AddFlightServlet\" method=\"post\">\n");
      out.write("   \n");
      out.write("  Enter Flight Number<input type=\"text\" name=\"flightNumber\"><br/>\n");
      out.write("  Enter Date of Flight<input type=\"datetime\" name=\"dto_flight\" id=\"datepicker\"><br/>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("   <label>Source Airport</label>\n");
      out.write("   	<select name=\"dep_airportCode\">\n");
      out.write("   		<option value=\"-1\">Select Airport\n");
      out.write("   		  ");

   		 	  String query="select * from dep_airport";
			  Connection connection=null;
			  Class.forName("com.mysql.cj.jdbc.Driver");
			  connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/mytrgdb",
						"root",
						"root");
			  Statement statement = connection.createStatement();
			  ResultSet rs=statement.executeQuery(query);
			  
			  while(rs.next())
			  {
				  
				
      out.write("\n");
      out.write("				<option value=\"");
      out.print(rs.getString("airport_name"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("airport_name"));
      out.write("</option>\n");
      out.write("				");

			  } 
   		  
      out.write("\n");
      out.write("   		</option>\n");
      out.write("   	</select>\n");
      out.write("    <br/>\n");
      out.write("    \n");
      out.write("    <label>Destination Airport</label>\n");
      out.write("    <select name=\"arr_airportCode\">\n");
      out.write("        <option value=\"-1\">Select Airport\n");
      out.write("        ");

        	String query1="select * from place_airport";
        	Connection connection1=null;
        	Class.forName("com.mysql.cj.jdbc.Driver");
        	connection1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mytrgdb",
					"root",
					"root");
        	Statement statement1 = connection1.createStatement();
        	ResultSet rs1=statement1.executeQuery(query1);
        	
        	while(rs1.next())
        	{
        		
      out.write("\n");
      out.write("        		<option value=\"");
      out.print(rs1.getString("airport_name"));
      out.write('"');
      out.write('>');
      out.print(rs1.getString("airport_name"));
      out.write("</option>\n");
      out.write("        		");

        	}	
        
      out.write("\n");
      out.write("        </option>\n");
      out.write("    </select>\n");
      out.write("   	<br/>\n");
      out.write("   	<label>Airline </label>\n");
      out.write("   	<select name=\"airlineId\">	\n");
      out.write("   	 	<option value=\"-1\">Select Airport</option>\n");
      out.write("   	 	");

   	 		try
   	 		{
   	 			  String query2="select * from airline";
   	 			  Connection connection2=null;
   				  Class.forName("com.mysql.cj.jdbc.Driver");
   				  connection2=DriverManager.getConnection("jdbc:mysql://localhost:3306/mytrgdb",
   							"root",
   							"root");
   				  Statement statement2 = connection2.createStatement();
   				  ResultSet rs2=statement2.executeQuery(query2);
   				
   				  while(rs2.next())
   				  {
   					  
      out.write("\n");
      out.write("   					     <option value=\"");
      out.print(rs2.getString("airline_code"));
      out.write('"');
      out.write('>');
      out.print(rs2.getString("airline_name"));
      out.write("</option>\n");
      out.write("   					  ");

   				  }
   	 		}
   	 		catch(ClassNotFoundException |SQLException ex)
   	 		{
   	 			ex.printStackTrace();
   	 		}
   	 	
      out.write("\n");
      out.write("   	</select>\n");
      out.write("   	<br/>\n");
      out.write("   	<br/>\n");
      out.write("   \n");
      out.write("   Ticket Price<input type=\"text\" name=\"ticketPrice\"><br/>\n");
      out.write("    Number of seats<input type=\"text\" name=\"noofSeats\"><br/>\n");
      out.write("   	<input type=\"submit\" value=\"Add\">\n");
      out.write("  \n");
      out.write("   </form>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
